import type { BudgetData, Currency } from '../firestore/types';

// Mirrors DefaultPreferences.swift — these are the built-in options the iOS app ships with.
// Firestore only stores user-added custom entries on top of these defaults.

export const DEFAULT_CATEGORIES: BudgetData[] = [
  { name: 'Earned Income', emoji: '💵', type: 'category', parent: null },
  { name: 'Entertainment', emoji: '🎬', type: 'category', parent: null },
  { name: 'Family', emoji: '👨‍👩‍👧‍👦', type: 'category', parent: null },
  { name: 'Food', emoji: '🍲', type: 'category', parent: null },
  { name: 'Friends', emoji: '👫', type: 'category', parent: null },
  { name: 'Fruits', emoji: '🍎', type: 'category', parent: null },
  { name: 'Grants', emoji: '🤲', type: 'category', parent: null },
  { name: 'Groceries', emoji: '🛒', type: 'category', parent: null },
  { name: 'Health', emoji: '❤️', type: 'category', parent: null },
  { name: 'Home', emoji: '🏠', type: 'category', parent: null },
  { name: 'Investment', emoji: '📈', type: 'category', parent: null },
  { name: 'Learning', emoji: '📚', type: 'category', parent: null },
  { name: 'Passive Income', emoji: '💰', type: 'category', parent: null },
  { name: 'Payment', emoji: '💳', type: 'category', parent: null },
  { name: 'Personal Care', emoji: '⭐️', type: 'category', parent: null },
  { name: 'Transportation', emoji: '🚗', type: 'category', parent: null },
  { name: 'Utilities', emoji: '⚡', type: 'category', parent: null },
];

export const DEFAULT_SUBCATEGORIES: BudgetData[] = [
  { name: 'Aircon Service', emoji: '❄️', type: 'sub_category', parent: 'Utilities' },
  { name: 'Apple', emoji: '🍎', type: 'sub_category', parent: 'Fruits' },
  { name: 'Attractions', emoji: '🎢', type: 'sub_category', parent: 'Entertainment' },
  { name: 'Auto', emoji: '🛺', type: 'sub_category', parent: 'Transportation' },
  { name: 'Banana', emoji: '🍌', type: 'sub_category', parent: 'Fruits' },
  { name: 'Beverages', emoji: '🥤', type: 'sub_category', parent: 'Food' },
  { name: 'Bicycle', emoji: '🚲', type: 'sub_category', parent: 'Transportation' },
  { name: 'Bike', emoji: '🚲', type: 'sub_category', parent: 'Transportation' },
  { name: 'Bonus', emoji: '🎉', type: 'sub_category', parent: 'Earned Income' },
  { name: 'Books', emoji: '📚', type: 'sub_category', parent: 'Learning' },
  { name: 'Breakfast', emoji: '🍳', type: 'sub_category', parent: 'Food' },
  { name: 'Bus', emoji: '🚌', type: 'sub_category', parent: 'Transportation' },
  { name: 'Car', emoji: '🚗', type: 'sub_category', parent: 'Transportation' },
  { name: 'Checkups', emoji: '👩‍⚕️', type: 'sub_category', parent: 'Health' },
  { name: 'Credit card', emoji: '💳', type: 'sub_category', parent: 'Payment' },
  { name: 'Cucumber', emoji: '🥒', type: 'sub_category', parent: 'Fruits' },
  { name: 'Curd', emoji: '🥄', type: 'sub_category', parent: 'Groceries' },
  { name: 'Debt', emoji: '💳💰', type: 'sub_category', parent: 'Payment' },
  { name: 'Dinner', emoji: '🍽️', type: 'sub_category', parent: 'Food' },
  { name: 'Dragon Fruit', emoji: '🐉', type: 'sub_category', parent: 'Fruits' },
  { name: 'Dress', emoji: '👗', type: 'sub_category', parent: 'Personal Care' },
  { name: 'Durian', emoji: '🍈', type: 'sub_category', parent: 'Fruits' },
  { name: 'Eatables', emoji: '🍲', type: 'sub_category', parent: 'Food' },
  { name: 'Eyebrows', emoji: '👁️', type: 'sub_category', parent: 'Personal Care' },
  { name: 'Flight', emoji: '✈️', type: 'sub_category', parent: 'Transportation' },
  { name: 'Flowers', emoji: '💐', type: 'sub_category', parent: 'Groceries' },
  { name: 'Fruits', emoji: '🍇', type: 'sub_category', parent: 'Groceries' },
  { name: 'Game', emoji: '🎮', type: 'sub_category', parent: 'Entertainment' },
  { name: 'Gold', emoji: '🏆', type: 'sub_category', parent: 'Investment' },
  { name: 'Grapes', emoji: '🍇', type: 'sub_category', parent: 'Fruits' },
  { name: 'Guava', emoji: '🍈', type: 'sub_category', parent: 'Fruits' },
  { name: 'Haircut', emoji: '💇‍♂️', type: 'sub_category', parent: 'Personal Care' },
  { name: 'HairDye', emoji: '💆‍♂️', type: 'sub_category', parent: 'Personal Care' },
  { name: 'Hardware', emoji: '🔧', type: 'sub_category', parent: 'Learning' },
  { name: 'Hindi', emoji: '🇮🇳', type: 'sub_category', parent: 'Learning' },
  { name: 'Honeydew', emoji: '🍈', type: 'sub_category', parent: 'Fruits' },
  { name: 'Insurance', emoji: '🛡️', type: 'sub_category', parent: 'Investment' },
  { name: 'Internet', emoji: '🌐', type: 'sub_category', parent: 'Utilities' },
  { name: 'Items', emoji: '🛍️', type: 'sub_category', parent: 'Personal Care' },
  { name: 'Jackfruit', emoji: '🍈', type: 'sub_category', parent: 'Fruits' },
  { name: 'Land', emoji: '🏞️', type: 'sub_category', parent: 'Investment' },
  { name: 'Lunch', emoji: '🍱', type: 'sub_category', parent: 'Food' },
  { name: 'Mango', emoji: '🥭', type: 'sub_category', parent: 'Fruits' },
  { name: 'Milk', emoji: '🥛', type: 'sub_category', parent: 'Groceries' },
  { name: 'Mobile', emoji: '📱', type: 'sub_category', parent: 'Utilities' },
  { name: 'Movie', emoji: '🎬', type: 'sub_category', parent: 'Entertainment' },
  { name: 'Naval', emoji: '🍊', type: 'sub_category', parent: 'Fruits' },
  { name: 'Non-Veg', emoji: '🍗', type: 'sub_category', parent: 'Groceries' },
  { name: 'Office', emoji: '🏢', type: 'sub_category', parent: 'Friends' },
  { name: 'Orange', emoji: '🍊', type: 'sub_category', parent: 'Fruits' },
  { name: 'Other Grants', emoji: '🤲', type: 'sub_category', parent: 'Grants' },
  { name: 'Others', emoji: '💼', type: 'sub_category', parent: 'Friends' },
  { name: 'Others', emoji: '💼', type: 'sub_category', parent: 'Personal Care' },
  { name: 'Papaya', emoji: '🍑', type: 'sub_category', parent: 'Fruits' },
  { name: 'Passive Income', emoji: '💰', type: 'sub_category', parent: 'Earned Income' },
  { name: 'Persimmon', emoji: '🍑', type: 'sub_category', parent: 'Fruits' },
  { name: 'Pomegranate', emoji: '🍑', type: 'sub_category', parent: 'Fruits' },
  { name: 'PUB', emoji: '🍺', type: 'sub_category', parent: 'Utilities' },
  { name: 'Relatives', emoji: '👨‍👩‍👧‍👦', type: 'sub_category', parent: 'Family' },
  { name: 'Rent', emoji: '🏠', type: 'sub_category', parent: 'Home' },
  { name: 'Rental Income', emoji: '💰', type: 'sub_category', parent: 'Passive Income' },
  { name: 'Salary', emoji: '💵', type: 'sub_category', parent: 'Earned Income' },
  { name: 'Stocks', emoji: '📈', type: 'sub_category', parent: 'Investment' },
  { name: 'Tax', emoji: '📝', type: 'sub_category', parent: 'Payment' },
  { name: 'Taxi', emoji: '🚖', type: 'sub_category', parent: 'Transportation' },
  { name: 'Television', emoji: '📺', type: 'sub_category', parent: 'Utilities' },
  { name: 'Things', emoji: '🛍️', type: 'sub_category', parent: 'Home' },
  { name: 'Train', emoji: '🚆', type: 'sub_category', parent: 'Transportation' },
  { name: 'Travel', emoji: '✈️', type: 'sub_category', parent: 'Entertainment' },
  { name: 'TV', emoji: '📺', type: 'sub_category', parent: 'Entertainment' },
  { name: 'Vegetables', emoji: '🌽', type: 'sub_category', parent: 'Groceries' },
  { name: 'Visa', emoji: '🛂', type: 'sub_category', parent: 'Transportation' },
  { name: 'Website', emoji: '🌐', type: 'sub_category', parent: 'Learning' },
];

export const DEFAULT_PAYMENTS: BudgetData[] = [
  { name: 'Cash', emoji: '💵', type: 'payment', parent: null },
  { name: 'Debit Card', emoji: '💳', type: 'payment', parent: null },
  { name: 'Credit Card', emoji: '💳', type: 'payment', parent: null },
  { name: 'Account', emoji: '🏦', type: 'payment', parent: null },
  { name: 'PayLah', emoji: '💳', type: 'payment', parent: null },
  { name: 'UPI', emoji: '💳', type: 'payment', parent: null },
];

export const DEFAULT_ACCOUNTS: BudgetData[] = [
  { name: 'Monthly Budget', emoji: '💼', type: 'account', parent: null },
];

export const DEFAULT_CURRENCY: Currency = {
  name: 'Singapore Dollar',
  code: 'SGD',
  symbol: '$',
};

// Matches DefaultPreferences.defaultEntries in iOS
export const DEFAULT_ENTRIES: Record<string, string> = {
  account: 'Monthly Budget',
};
